echo "Repair the rofi style comment that a theme switch rewrote"

# theme-switcher.sh rewrote the url() reference in each rofi style.rasi with
#
#   sed -i "s|images/wallpaper\.[a-z]*|images/wallpaper.$WP_EXT|"
#
# and that pattern also matched the header of the same file, which reads
#
#   /* This file is yours, with one exception: the line naming
#      images/wallpaper.<ext> is rewritten on every theme switch so it matches
#      the wallpaper's actual format. Everything else here is kept. */
#
# [a-z]* matched nothing before "<ext>", so every theme switch turned that into
# images/wallpaper.jpg<ext>, and the one promise the file makes about itself was
# broken by the line describing it.
#
# It also made the file differ from the shipped one, and style.rasi carries no
# "Do not edit this file" header, so hyprsimple-update.sh counts it as the
# user's own copy. An update touching style.rasi would name it as a file they
# have their own version of, over a difference hyprsimple made.
#
# Only the exact damage is repaired: images/wallpaper.<something-lowercase><ext>
# back to images/wallpaper.<ext>. A file edited by hand in any other way is not
# touched, and neither is one that never had the header.

repaired=0
for rofi_type in launcher powermenu; do
  style="$HOME/.config/rofi/$rofi_type/style.rasi"
  [[ -f $style ]] || continue

  grep -q 'images/wallpaper\.[a-z][a-z]*<ext>' "$style" || continue

  sed -i 's|images/wallpaper\.[a-z][a-z]*<ext>|images/wallpaper.<ext>|' "$style"
  repaired=$((repaired + 1))
done

if (( repaired > 0 )); then
  echo "  Put the comment back in $repaired rofi style file(s). Your own edits are untouched."
else
  echo "  Nothing to repair."
fi
