local vars = require("default.hypr.vars")
local home = os.getenv("HOME")

hl.bind("SUPER + X",         hl.dsp.exec_cmd(home .. "/.local/bin/hypr-logout.sh"),             { description = "Logout" })
hl.bind("SUPER + SHIFT + L", hl.dsp.exec_cmd("hyprlock"),                                       { description = "Lock Screen" })
hl.bind("SUPER + ESCAPE",    hl.dsp.exec_cmd(vars.powermenu),                                   { description = "Power Menu" })
hl.bind("CTRL + ESCAPE",     hl.dsp.exec_cmd(home .. "/.local/bin/hyprsimple-restart-bar.sh --toggle"), { description = "Toggle Bar" })
hl.bind("SUPER + SHIFT + M", hl.dsp.exec_cmd(home .. "/.local/bin/monitor-mirror-toggle.sh"),   { description = "Toggle Monitor Mirror" })
hl.bind("SUPER + CTRL + V",  hl.dsp.exec_cmd(home .. "/.local/bin/virtual-mirror-toggle.sh"),   { description = "Toggle Virtual Mirror" })
hl.bind("SUPER + N",         hl.dsp.exec_cmd(home .. "/.local/bin/toggle-nightlight.sh"),       { description = "Toggle Nightlight" })
hl.bind("SUPER + SHIFT + I", hl.dsp.exec_cmd(home .. "/.local/bin/toggle-idle.sh"),             { description = "Toggle Idle Prevention" })
hl.bind("SUPER + D",         hl.dsp.exec_cmd(home .. "/.local/bin/notification-dismiss.sh"),    { description = "Dismiss Notifications" })
hl.bind("SUPER + S",         hl.dsp.exec_cmd(vars.barPanel .. "volume"),                        { description = "Sound (panel: volume and output device)" })
hl.bind("SUPER + slash",     hl.dsp.exec_cmd(home .. "/.local/bin/show-keybindings.sh"),        { description = "Show Keybindings" })
